# Generated by Django 2.0 on 2018-02-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, unique=True)),
                ('precio', models.FloatField(max_length=4)),
                ('creditos_clase', models.PositiveSmallIntegerField()),
                ('creditos_openBox', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=25)),
                ('apellido2', models.CharField(max_length=25)),
                ('dni', models.CharField(max_length=9)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='Hombre', max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('tipo', models.CharField(choices=[('Entrenador', 'Entrenador'), ('Atleta', 'Atleta')], default='Atleta', max_length=12)),
                ('foto', models.ImageField(default='fotos/user.png', upload_to='fotos')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('bono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossfit.Bono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
