# Generated by Django 2.0 on 2018-02-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad_max', models.PositiveSmallIntegerField()),
                ('m2', models.FloatField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossfit.Perfil')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossfit.Clase')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='clase',
            field=models.ManyToManyField(through='crossfit.Reservar', to='crossfit.Clase'),
        ),
    ]
