# Generated by Django 2.0 on 2018-02-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0004_remove_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
