# Generated by Django 2.0 on 2018-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0006_auto_20180212_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horaFin',
            field=models.TimeField(max_length=12),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaInicio',
            field=models.TimeField(max_length=12),
        ),
    ]
