# Generated by Django 2.0 on 2018-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0008_auto_20180213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/user.png', upload_to='fotos'),
        ),
    ]
