# Generated by Django 2.0 on 2018-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0009_auto_20180214_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservar',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservar',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
