# Generated by Django 2.0 on 2018-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0011_auto_20180214_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservar',
            name='horaFin',
        ),
        migrations.AddField(
            model_name='reservar',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
