# Generated by Django 2.0 on 2018-02-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0012_auto_20180214_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fechaNacimiento',
        ),
    ]
