# Generated by Django 2.0 on 2018-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0014_perfil_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
