# Generated by Django 2.0 on 2018-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0015_auto_20180215_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bono',
            name='creditos_openBox',
        ),
    ]
