# Generated by Django 2.0 on 2018-02-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0016_remove_bono_creditos_openbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ejercicios', models.CharField(max_length=400)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crossfit.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ejercicios', models.CharField(max_length=400)),
            ],
        ),
    ]
