# Generated by Django 2.0 on 2018-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0017_entreno_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficial',
            name='categoria',
            field=models.CharField(choices=[('The Heroes', 'Héroes'), ('The Girls', 'Girls')], default='The Heroes', max_length=20),
        ),
    ]
