# Generated by Django 2.0 on 2018-02-20 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crossfit', '0019_auto_20180217_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='m2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crossfit.Actividad'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crossfit.Clase'),
        ),
        migrations.AlterField(
            model_name='reservar',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
